# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.SmallIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='article',
            name='read',
            field=models.SmallIntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
