# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190208_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='说说')),
                ('picture', models.ImageField(upload_to='talk/%Y%m/%d', verbose_name='说说图片')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': '标签管理', 'verbose_name_plural': '标签管理'},
        ),
    ]
