# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190209_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'verbose_name': '说说管理', 'verbose_name_plural': '说说管理'},
        ),
        migrations.AlterField(
            model_name='talk',
            name='picture',
            field=models.ImageField(null=True, upload_to='talk/%Y%m/%d', verbose_name='说说图片'),
        ),
    ]
