# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190209_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='图片描述')),
                ('picture', models.ImageField(upload_to='home/%Y%m', verbose_name='首页轮播图片')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
