# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_indexpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='留言内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '留言板管理',
                'verbose_name_plural': '留言板管理',
            },
        ),
        migrations.AlterModelOptions(
            name='indexpicture',
            options={'verbose_name': '首页轮播管理', 'verbose_name_plural': '首页轮播管理'},
        ),
    ]
