# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190209_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.SmallIntegerField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('integral', models.SmallIntegerField(max_length=11, verbose_name='积分')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
