# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='integral',
            field=models.SmallIntegerField(default=0, max_length=11, verbose_name='积分'),
        ),
    ]
