# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 19:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190209_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='integral',
            field=models.SmallIntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误!')], verbose_name='手机号'),
        ),
    ]
